# Generated by Django 4.1.3 on 2022-12-13 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eduone', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='eduone.question'),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('action', models.CharField(max_length=225)),
                ('account', models.IntegerField()),
                ('account_name', models.CharField(max_length=225)),
                ('bank', models.CharField(max_length=225)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Succesful', 'Succesful')], default='Pending', max_length=225, null=True)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('action', models.CharField(max_length=225)),
                ('tx_ref', models.CharField(max_length=225)),
                ('completed', models.BooleanField(default=False)),
                ('trans_id', models.CharField(blank=True, max_length=225, null=True)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
