# Generated by Django 4.1.3 on 2022-12-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduone', '0005_alter_transaction_options_alter_withdraw_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=225)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Succesful', 'Succesful')], default='Pending', max_length=225, null=True),
        ),
    ]
